### ISSUE TITLE
支援從師大選課系統匯入課程

### ISSUE THREAD

**Issue by Bogay** [UniCourse-TW/roadmap#2]
目前已有 [JacobLinCool/NTNU-Course-Crawler](https://github.com/JacobLinCool/NTNU-Course-Crawler)，所以只要可以把這些資料轉換成 model 我想就可以了。

**Comment by skyhong2002** [comment]
如果要讓社群 Work 起來的話勢必不能只有師大的課程，或許也要想像要如何支援其他學校的課程，或是要在一開始做哪些調整，讓之後加入其他學校課程時會比較少衝突

**Comment by skyhong2002** [comment]
@JacobLinCool 有訂另外一個稱為 Course pack 的東東
