### ISSUE TITLE
Review 專案孵化競賽評審回饋

### ISSUE THREAD

**Issue by skyhong2002** [UniCourse-TW/roadmap#26]
> 回饋1：
> 能統整全國大學課程是不錯的目標，若能收集夠多大學的課程，這會是很有價值的資料，不過收集夠多大學也是個挑戰，建議可以優先設計一個大學地圖，列出台灣哪些大學已經有資料，哪些大學還沒有資料，來凸顯還沒資料的大學，以吸引該大學的人來提供資料，並且也要早一點設計 schema ，讓提供資料這件事可以分散處理。

> 回饋2：
> 哇，這根本是大學課程的 Google Map，超級期待成果產出。有幾個我目前想到可能會遇到的困難
> 1. 課程名稱可能會改變，要怎麼連結新舊名稱同屬一個課程，同樣的課程也可能有不同的授課老師，資料庫的建立除了符合 data base 之外，可以列出幾種主要的變動來作為設計參考
> 2. 評分系統可能要特別注意建立之後的一些留言機制，可以從現有有評分機制的網站去思考，未來建立之後管理規範
> - 洗負評防範
> - 怎麼證明他真的有修課過
> - 跟 dcard 合作？增加評分留言的人
> - 是否要給老師平反的空間
> 

> 回饋3：
> 想法與規畫都十分具體令人期待。在大學整併的過程中，或許能帶給大學教育另一種打破校園上課的思維。目前已有不少大學有校際修課和學分認證的規範，似乎也能整合進這個平台之中。	

> 回饋4：
> 若無法直接取得各大學端開課資料庫，如何讓平台資料庫可以穩定持續更新。

> 回饋5：
> 我相信已經存在不少關於大學課程的相關平台，欠缺的只是一種整合。其次，對於教授的評分或者上課方式，是否只有學生方的意見，欠缺教學者一方的意見？

**Comment by antingchao** [comment]
我簡單整理了評審們的問題：

1. 收集跨校資料（課程資料、校際修課和學分認證的規範）
2. 課程的界定（課程名稱改變、同課程不同老師）
3. 評分留言控管（洗負評防範、確認評分者真的有修課、增加評分留言的人）
4. 加入教學者意見

**Comment by antingchao** [comment]
解決方式提案

加入教學者一方的意見
1. 留言功能：讓大家（包括教學者）能針對一篇心得文給予評論（贊同或平反）
2. 教學者專用發文介面：可能可以設計老師專用的發文介面與文章類別（？）只是這樣就要驗證教師身分。而且其實目前的發文介面也夠讓教學者填了。

**Comment by Bogay** [comment]
> 回饋1：
> ... 並且也要早一點設計 schema ，讓提供資料這件事可以分散處理。

這點目前已經有設計 Course Pack 的格式作為中間層，所以聽起來算是有達到。但或許可以再嘗試多蒐集一些學校的資料來討論是否會在轉換上遇到困難，另外需要支援動態欄位作為最後的 fallback 可能好點，我記得 course pack 有支援，但我們好像沒有匯入系統測試過？

> 回饋2：
> ...
> 
> 1. 課程名稱可能會改變，要怎麼連結新舊名稱同屬一個課程，同樣的課程也可能有不同的授課老師，資料庫的建立除了符合 data base 之外，可以列出幾種主要的變動來作為設計參考

我覺得不用到糾結是否是同一堂課，就算名稱跟老師都不變，不同年開課還是可能會有差別。但如果有辦法透過一些比較自動化的方式替不同學期、年份的課程建立關聯或許可以降低搜尋的難度。

> 2. 評分系統可能要特別注意建立之後的一些留言機制，可以從現有有評分機制的網站去思考，未來建立之後管理規範
>
> * 洗負評防範

我們的帳號應該也算是有驗證過身分，所以應該比較能夠避免一堆 bot 去刷評分。這在之上額外做點 captcha 驗證不曉得是否足夠？

> * 怎麼證明他真的有修課過

目前沒想到足夠自動化的方式，之前程設要確認修課資格也是我跑到系辦人工檢查名單。不過我認為網路上的使用者評論難免會出現誤差，所以不需要到追求完全正確？課程本身資料的正確性比較是我們可以掌控的。

> * 跟 dcard 合作？增加評分留言的人

如果 Dcard 有提供 OAuth 機制的話感覺也是個方法，由 Dcard 驗證學生身分應該算是可信度夠高。

> 回饋3：
> 想法與規畫都十分具體令人期待。在大學整併的過程中，或許能帶給大學教育另一種打破校園上課的思維。目前已有不少大學有校際修課和學分認證的規範，似乎也能整合進這個平台之中。

修課跟學分認證，要讓學校採計感覺困難度比較高？但單純提供資訊的話感覺還在學生組織有辦法達成的範疇，像是提供過往學分被承認的紀錄，這些資料對於轉學或是研究所非直升的同學都會有幫助。

> 回饋4：
> 若無法直接取得各大學端開課資料庫，如何讓平台資料庫可以穩定持續更新。

不曉得由使用者上傳後人工審核會不會是個可行的方式？但這人力需求偏高。
