### ISSUE TITLE
[零時先輩] 專案永續／社群經營方法

### ISSUE THREAD

**Issue by skyhong2002** [UniCourse-TW/roadmap#28]
因為 Carina 有前端的 Loading，因此想把這次的規劃交給 Anting 負責

- 如何利用 FB/IG 進行專案宣傳
- 社群經營該注意的地方，如果有文本可以參考更好

**Comment by antingchao** [comment]
時間：1/16(一) 晚上 20:00-21:00（暫定，要跟先輩約才確定）
目前能到：安庭、可菡、Sky

問題整理：
- 如何「吸引」並「留住」使用者、開發夥伴（並且要有跨校成員）
- 如何讓各校校方對 UniCourse 保持開放態度（關於課程資料搜集的部分）
- 如何讓 g0v 或其他贊助單位看得到我們的成果
- 如何利用 FB/IG 進行專案宣傳（貼文內容、頻率）
- 社群經營該注意的地方（如果有文本可以參考更好）

**Comment by antingchao** [comment]
諮詢記錄
https://g0v.hackmd.io/zPRuCunNSsimAZ1CrlbzWQ?both
