### ISSUE TITLE
[零時先輩] 大學課程資料庫開發維護細節

### ISSUE THREAD

**Issue by skyhong2002** [UniCourse-TW/roadmap#29]
- 備份相關建議
- 監控及相關 SOP

本來想找有 SRE 經驗的，但發現似乎沒有人有寫上去
交給 Bogay

**Comment by skyhong2002** [comment]
請 @uier update

**Comment by Bogay** [comment]
已寄信，等待回覆中。

**Comment by skyhong2002** [comment]
https://hackmd.io/@UniCourse/overview/https%3A%2F%2Fg0v.hackmd.io%2F%40jothon%2Frk-qaipvs
