### ISSUE TITLE
申請到贊助之前我們要怎麼架機器

### ISSUE THREAD

**Issue by skyhong2002** [UniCourse-TW/roadmap#3]

**Comment by uier** [comment]
只是 for 開發用的話 AWS 免費額度看夠不夠用

**Comment by skyhong2002** [comment]
那把之後把 Volumes 從 AWS 上搬到 GCP 是方便的ㄇ

**Comment by JacobLinCool** [comment]
應該把 docker volume 打包成 tar 搬出來就好了。
但可能要查一下數據出口價格？

**Comment by skyhong2002** [comment]
CNTUG 有提供免費的 Cloud 平台給社群朋友們使用，這裡是 [申請表單](https://forms.gle/rqahTzwQaamkp7eb9) 和 [更多資訊](https://github.com/cloud-native-taiwan/Infra-Labs-Docs/blob/main/user-guide/faq.md)。如果最後 GDSC 沒辦法給資源的話，或許 CNTUG 是個選擇（甚至一起申請也可以）。雖然可能和其他 GDSC 跨校合作的可能性就會比較困難，但也相對比較沒有限制（？
如果要申請的話可以問 @steveyiyo

**Comment by ichiehg0v** [comment]
我是 g0v 參與者 @ichieh，之前有其他零時小學校的獲獎團隊，申請使用國網中心的資源，我不確定現在有沒有適合你們的資源，或是也可以到 g0v slack 問問看其他會寫程式的人知不知道有相關資源可以運用。
https://iservice.nchc.org.tw/nchc_service/nchc_service_qa.php?target=16

**Comment by skyhong2002** [comment]
因目前資源需求不高，故先以 CNTUG 以及 GDSC 贊助的機器就豪

**Comment by Bogay** [comment]
@skyhong2002 這應該可以關了吧？

**Comment by skyhong2002** [comment]
是的感謝，不過 GDSC 的贊助協調目前暫緩
