### ISSUE TITLE
撰寫 UniCourse 課程匯入指南

### ISSUE THREAD

**Issue by skyhong2002** [UniCourse-TW/roadmap#31]
https://hackmd.io/@noj/unicourse/%2FAyUxAgKYQjihTCtRP11BDw

**Comment by skyhong2002** [comment]
還需要簡化版的 Example

**Comment by JacobLinCool** [comment]
> 還需要簡化版的 Example

done

**Comment by skyhong2002** [comment]
https://hackmd.io/@UniCourse/BkCSjO2Ys
