### ISSUE TITLE
聯絡教育部課程資源網爬取資料的可能性

### ISSUE THREAD

**Issue by skyhong2002** [UniCourse-TW/roadmap#32]
雖然目前搜集課程的方式目前預計以尋找各校負責人為主，但有鑒於教育部有課程資源網。他的創立主旨是提供社會大眾以快速、便民的方式做各大學校院之課程查詢，並提供相關數據提供參考使用。（參考自首頁）或許他們有我們可以參考的資源。

> [教育部課程資源網](https://course-tvc.yuntech.edu.tw/web_nu/search_course.aspx)
> 課程工作小組聯絡資訊
> TEL:(05)537-2747
> MAIL:[ddpc@yuntech.edu.tw](mailto:ddpc@yuntech.edu.tw)

**Comment by skyhong2002** [comment]
要詢問到的內容包含：

- 是否有可供連結的 API 而非單一匯出的 csv 等格式
- 是否能存取每一堂課程在該學校的課程代碼，或是任何唯一識別標籤
- 請問他們是如何向各學校獲取課程資料，以及是否能夠透露聯絡管道
- 課程資料庫更新的時間區間，可以以 111-2 作為例子 #30 

@calico301519

**Comment by skyhong2002** [comment]
是說 @JacobLinCool 你覺得還有什麼是可以問他們的嗎？

**Comment by uier** [comment]
> 要詢問到的內容包含：
> 
> * 是否有可供連結的 API 而非單一匯出的 csv 等格式
> * 是否能存取每一堂課程在該學校的課程代碼，或是任何唯一識別標籤
> * 請問他們是像個學校獲取課程資料的管道，以及是否能夠透露聯絡管道
> * 課程資料庫更新的時間區間，可以以 111-2 作為例子 [[零時先輩] 跨校資料整合方法實作 #30](https://github.com/UniCourse-TW/UniCourse/issues/30)


第三行有打錯字嗎？我好像看不太懂

**Comment by skyhong2002** [comment]
> 第三行有打錯字嗎？我好像看不太懂

是打錯字沒錯，已修正。
請問他們各學校獲取課程資料的管道，藉此參考他們的方式並確認他們課程資料的來源

**Comment by JacobLinCool** [comment]
目前沒有想到其他的，你大概都把我想問的都打出來了。

依照優先度我自己會這樣排：

資料準確？ - 對應問題三
資訊即時？ - 對應問題四
取得方便？ - 對應問題一

話說這個資料有明確授權使用方式範圍嗎？

**Comment by calico301519** [comment]
好的！已收到

**Comment by calico301519** [comment]
GDSC NTU 團隊您好：

我們是 UniCourse ，是由師大資工學生組成的團隊（其中也包含 GDSC NTNU 成員），致力於開發方便大學生們查詢和詢問課程資訊的平台。由於目前尚在開發階段，需要尋找各校有志之士一起完善網站，想詢問貴團隊是否有興趣參與台大部分的作業，主要工作內容如下：

1. 討論穩定且有效的課程爬蟲模式
2. 介紹有興趣的成員負責匯入 111-2 的台大課程

如果有更進一步的問題和合作意願，歡迎回信，我們將盡快進行回覆！

祝 新春愉快
UniCourse 團隊 敬上

（這是擬定給各校 GDSC 或是資訊相關的模板！><）

**Comment by calico301519** [comment]
教育部課程資源網 您好：

我們是 UniCourse ，是由師大資工學生組成的團隊，目前正致力於開發方便大學生們查詢與詢問課程資訊的平台。由於目前尚在開發階段，在 case-study 的過程中，我們發現貴團隊有許多有價值的資訊紀錄，想詢問貴團隊是否方便提供：

1. 是否有可供連結的 API 而非單一匯出的 csv 等格式
2. 是否能存取每一堂課程在該學校的課程代碼，或是任何唯一識別標籤

另外，由於缺乏相關資訊，我們也想要了解貴團隊如何向各學校獲取課程資料，以及是否方便透露與它們的聯絡管道，並且想要了解貴團隊大略的課程資料庫更新時間區間（以111-2學期為例）

若有幸得到貴團隊的幫助，除了能有效推動高等教育資源的資訊流通外，我們也將會於 UniCourse 網站註明教育部課程資源網的協助，並且回報網站最終成果。如果有合作意願或是有進一步的問題想要詢問，歡迎逕行回覆，我們將盡快回答。

祝 新春愉快
UniCourse 團隊 敬上

這個是給教育部的擬信！

**Comment by calico301519** [comment]
目前想到可以寄信的對象：
（順序是優先順序）

台大：1. 學生會資訊部 2. 台大 GDSC 3. 台大資工系學會 4. 台大資管系學會

台科大：1. 台科大 GDSC 2. 台科大資工系學會 3. 台科大電資學院院學會 

成大：1. 成大 GDSC（我記得應該有但我剛剛莫名找不到嗚嗚）2. 成大 CCNS 電腦與網路愛好社 3. 成大資工系學會

其實我覺得系學會感覺不太可靠嗚嗚（看工作內容不太像是會做這個的）但感覺也不是不能試試嗚嗚嗚嗚

**Comment by calico301519** [comment]
教育部課程資源網 您好：

我們是 UniCourse ，是由師大資工學生組成的團隊，目前正致力於開發方便大學生們查詢與詢問課程資訊的平台。由於目前尚在開發階段，在 case-study 的過程中，我們發現貴團隊有許多有價值的資訊紀錄，想詢問貴團隊是否方便提供：

1. 是否有可供連結的 API 而非單一匯出的 csv 等格式
2. 是否能存取每一堂課程在該學校的課程代碼，或是任何唯一識別標籤

另外，由於缺乏相關資訊，我們也想要了解貴團隊如何向各學校獲取課程資料，以及是否方便透露與它們的聯絡管道，並且想要了解貴團隊大略的課程資料庫更新時間區間（以111-2學期為例）

若有幸得到貴團隊的幫助，除了能有效推動高等教育資源的資訊流通外，我們也將會於 UniCourse 網站註明教育部課程資源網的協助，並且回報網站最終成果。如果有合作意願或是有進一步的問題想要詢問，歡迎逕行回覆，我們將盡快回答。

祝 新春愉快
UniCourse 團隊 敬上

這個是給教育部的擬信！

**Comment by calico301519** [comment]
教育部課程資源網 您好：

我們是 UniCourse ，是由師大資工學生組成的團隊，目前正致力於開發方便大學生們查詢與詢問課程資訊的平台。由於目前尚在開發階段，在 case-study 的過程中，我們發現貴團隊有許多有價值的資訊紀錄，想詢問貴團隊是否方便提供：

1. 是否有可供連結的 API 而非單一匯出的 csv 等格式
2. 是否能存取每一堂課程在該學校的課程代碼，或是任何唯一識別標籤

另外，由於缺乏相關資訊，我們也想要了解貴團隊如何向各學校獲取課程資料，以及是否方便透露與它們的聯絡管道，並且想要了解貴團隊大略的課程資料庫更新時間區間（以111-2學期為例）

若有幸得到貴團隊的幫助，除了能有效推動高等教育資源的資訊流通外，我們也將會於 UniCourse 網站註明教育部課程資源網的協助，並且回報網站最終成果。如果有合作意願或是有進一步的問題想要詢問，歡迎逕行回覆，我們將盡快回答。

祝 新春愉快
UniCourse 團隊 敬上

這個是給教育部的擬信！

**Comment by skyhong2002** [comment]
已寄出。

**Comment by skyhong2002** [comment]
> 您好：
> 
> 此平台之課程資料都是由各校於規定時間內將該學年度所開設之課程上傳到此平台，目前僅提供查詢後匯出資料的方式，
> 只要在課程資源網查詢後的資料都可以匯出再依自己的需求加以使用，沒有額外提供其他資料授權，謝謝。
> 
> 敬祝  順心
>               課程網工作小組  敬上

cc @JacobLinCool
