### ISSUE TITLE
決選日報告準備

### ISSUE THREAD

**Issue by skyhong2002** [UniCourse-TW/roadmap#37]
- [x] 2/5 前會關閉 g0v 編輯功能
- [x] 2/9 中午前上傳簡報 + 影片
- [x] 2/11 決選日

**Comment by skyhong2002** [comment]
影片內容包含

- 搜尋課程
- 顯示課程
- 分享課程

交給 @antingchao

**Comment by skyhong2002** [comment]
我們把檔案都放在 Google Drive 好了，包含簡報和影片：
https://drive.google.com/drive/folders/1rKQ9Vqai7i8DI0WYmFQJSJ7SFlGy388D?usp=share_link

有把編輯權限給各位 @UniCourse-TW/maintainer 了：
![Image](https://user-images.githubusercontent.com/29522167/216820396-3cc462a7-23d5-4df7-a672-60794b2e5671.png)

**Comment by antingchao** [comment]
影片我放上去囉！請幫忙檢查一下，感謝！

**Comment by skyhong2002** [comment]
附上 g0v 零時小學校評分基準

- 影響力 Impact（提案整體願景的影響力）
- 可重複使用性 Reusability（成果的元件是否辦法為其他專案使用）
- 可行性 Feasibility（技術可行與社會或預期使用者採納的可能性）
- 完成度 Completeness（提案對於整體提案願景的完成度、貢獻度或含括範圍）（加權x1.5）
- 創意度 Creativity （提案內容是否有別於過往類似案例的模式）
